apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{.Values.nameOverride}}
  namespace: {{.Values.nameOverride}}
  labels:
    app: {{.Values.nameOverride}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.nameOverride}}
  template:
    metadata:
      labels:
        app: {{.Values.nameOverride}}
    spec:
      containers:
        - name: {{.Values.nameOverride}}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      restartPolicy: Always
