apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.nameOverride}}-service"
  namespace: {{.Values.nameOverride}}
spec:
  selector:
    app: {{.Values.nameOverride}}
  ports:
    - name: http
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}