name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Checkout do código fonte
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configuração do JDK para construir o projeto
      - name: Setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Step 3: Construir o projeto usando Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Login no DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/playground-gitops-argo-cd:${{ github.sha }}
